services:
  # Backend service
  - type: web
    name: my-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    
  # Frontend service
  - type: static
    name: my-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    envVars:
      - key: VITE_ENV
        fromService:
          name: my-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL